services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

    develop:
      ports:
        - 3000:3000
      volumes:
        - .:/app
        - /app/node_modules
