const { COLUMN } = require("../models/schema");

const majorList = [
  ["ACC", "Accounting"],
  ["AERO", "Aerospace Engineering"],
  ["ANES", "Ancient Near Eastern and Egyptian Studies"],
  ["ANTH", "Anthropology"],
  ["APPM", "Applied Mathematics"],
  ["ARTED", "Art Education"],
  ["ARTH", "Art History"],
  ["ASST", "Asian Studies"],
  ["ASTR", "Astronomy"],
  ["BIOC", "Biochemistry"],
  ["BIOL", "Biology"],
  ["BME", "Biomedical Engineering"],
  ["BIT", "Business Information Technology"],
  ["BMGT", "Business Management"],
  ["CHBI", "Chemical Biology"],
  ["CHEN", "Chemical Engineering"],
  ["CHEM", "Chemistry"],
  ["CHIN", "Chinese"],
  ["CIV", "Civil Engineering"],
  ["CLAS", "Classics"],
  ["COGS", "Cognitive Science"],
  ["COMS", "Communication Sciences"],
  ["CENG", "Computer Engineering"],
  ["CS", "Computer Science"],
  ["DANC", "Dance"],
  ["DSA", "Data Science and Analytics"],
  ["ECON", "Economics"],
  ["EE", "Electrical Engineering"],
  ["EPHY", "Engineering Physics"],
  ["ENGL", "English"],
  ["ENGGEO", "Environmental Geology"],
  ["ENVS", "Environmental Studies"],
  ["EVOB", "Evolutionary Biology"],
  ["FIN", "Finance"],
  ["FREN", "French"],
  ["FFS", "French and Francophone Studies"],
  ["GENE", "General Engineering"],
  ["GEOL", "Geological Sciences"],
  ["GERM", "German"],
  ["GERO", "Gerontological Studies"],
  ["HIST", "History"],
  ["HPS", "History and Philosophy of Science"],
  ["INTS", "International Studies"],
  ["JPN", "Japanese Studies"],
  ["MKT", "Marketing"],
  ["MSE", "Materials Science and Engineering"],
  ["MATH", "Mathematics"],
  ["MECH", "Mechanical Engineering"],
  ["MUS", "Music"],
  ["MUSED", "Music Education"],
  ["NSCI", "Natural Sciences"],
  ["NEUR", "Neuroscience"],
  ["NURS", "Nursing"],
  ["NUTR", "Nutrition"],
  ["NBM", "Nutritional Biochemistry and Metabolism"],
  ["ORIG", "Origins Sciences"],
  ["PHIL", "Philosophy"],
  ["PHYS", "Physics"],
  ["POSC", "Political Science"],
  ["PSE", "Polymer Science and Engineering"],
  ["PARCH", "Pre-architecture"],
  ["PSY", "Psychology"],
  ["RLST", "Religious Studies"],
  ["SOC", "Sociology"],
  ["SPAN", "Spanish"],
  ["STAT", "Statistics"],
  ["SCE", "Systems and Control Engineering"],
  ["SYSB", "Systems Biology"],
  ["TEED", "Teacher Education"],
  ["THAR", "Theater Arts"],
  ["WGSS", "Women's, Gender, and Sexuality Studies"],
  ["WLIT", "World Literature"],
  ["MATHPHYS", "Mathematics and Physics"],
];

const departmentList = [
  ["ACCT", "Accountancy"],
  ["ANAT", "Anatomy"],
  ["ANTH", "Anthropology"],
  ["APTC", "APT Center - Veterans Affairs"],
  ["ARTH", "Art History and Art"],
  ["ASTR", "Astronomy"],
  ["BAKN", "Baker Nord Center"],
  ["BAFI", "Banking and Finance"],
  ["BCVP", "Begun Ctr for Violence Prevent"],
  ["BIOC", "Biochemistry"],
  ["BCRN", "Biochemistry RNA center"],
  ["BETH", "Bioethics"],
  ["BIOLSCI", "Biological Sciences"],
  ["BIOL", "Biology"],
  ["BHI", "Biomed & Hlth Informatics"],
  ["BMEG", "Biomedical Engineering"],
  ["CANB", "Cancer Biology"],
  ["CVMS", "Cardiovascular and Metabolic Sciences"],
  ["CVRI", "Cardiovascular Research Institute"],
  ["CCCC", "Case Comprehensive Cancer Center"],
  ["CBPD", "Center for Blood Pressure Disorders"],
  ["CCHP", "Center for Child Health and Policy"],
  ["CGHD", "Center for Global Health and Diseases"],
  ["CIMR", "Center for Imaging Research"],
  ["CPBI", "Center for Proteomics and Bioinformatics"],
  ["CRGM", "Center for Regenerative Medicine"],
  ["CSHS", "Center for Science, Health, and Society"],
  ["CBEN", "Chemical and Biomolecular Engineering"],
  ["CHEM", "Chemistry"],
  ["CVEN", "Civil  and Environmental Engineering"],
  ["CLSC", "Classics"],
  ["CMNH", "Cleveland Museum of Natural History"],
  ["CTSR", "Clinical and Translational Research"],
  ["COGS", "Cognitive Science"],
  ["COSI", "Communication Science"],
  ["CSDS", "Computer and Data Sciences"],
  ["CENG", "Computer Engineering"],
  ["CIS", "Computing & Info Science"],
  ["DANC", "Dance"],
  ["DGA", "Dean/General Admin"],
  ["DERM", "Dermatology"],
  ["DESN", "Design and Innovation"],
  ["DHRI", "Digestive Health Research Institute"],
  ["EEPS", "Earth, Environmental, and Planetary Sciences"],
  ["ECON", "Economics"],
  ["EDUC", "Education"],
  ["ECSE", "Electrical, Computer and Systems Engineering"],
  ["ENGL", "English"],
  ["EBIO", "Epidemiology & Biostats"],
  ["EPCC", "Epilepsy Center at CCF"],
  ["FMCH", "Family Medicine & Community Health"],
  ["GENE", "Genetics and Genome Sciences"],
  ["GENM", "Genomic Medicine"],
  ["GEOL", "Geological Sciences"],
  ["GMSCCC", "GMS Comprehensive Cancer Ctr"],
  ["GMSCGHD", "GMS Ctr Global Hlth & Disease"],
  ["HSTY", "History"],
  ["IPIO", "Immunotherapy & Precision Immuno-Onocology"],
  ["INAM", "Inamori Center"],
  ["INBI", "Infection Biology"],
  ["INFD", "Infectious Diseases"],
  ["INFI", "Inflammation and Immunity"],
  ["ITMM", "Inst. For Trans Molecular Med"],
  ["IBMS", "Integrated Biomedicl Sci"],
  ["LAW", "Law"],
  ["LAWCP", "LAW - Clinical Programs"],
  ["LLM", "LLM US/Global Legal Studies"],
  ["EMAC", "Macromolecular Science and Engineering"],
  ["MGMT", "Management"],
  ["MSAS", "Mandel School of Applied Social Sci"],
  ["EMSE", "Materials Science and Engineering"],
  ["MCN", "Maternal/Child Nutrition"],
  ["MATH", "Mathematics, Applied Mathematics, and Statistics"],
  ["EMAE", "Mechanical and Aerospace Engineering"],
  ["MCV", "Med Cardiovascular Medicine UH"],
  ["MGI", "Med Gastroenterology UH"],
  ["MHO", "Med Hematology/Oncology UH"],
  ["MID", "Med Infectious Disease UH"],
  ["MSTP", "Med Scientist Trng Prg"],
  ["MEDI", "Medicine"],
  ["MEDMHMC", "Medicine MHMC"],
  ["MLIT", "Modern Languages and Literatures"],
  ["MBIO", "Molecular Biology and Microbiology"],
  ["MOLM", "Molecular Medicine"],
  ["MVIR", "Molecular Virology"],
  ["MORE", "MORE Center"],
  ["MUSC", "Music"],
  ["NIMIC", "National Initiative on Mixed-Income Communities"],
  ["NSUH", "Neurological Surgery UH"],
  ["NEUR", "Neurology"],
  ["NEUS", "Neurosciences"],
  ["NURS", "Nursing"],
  ["NTRN", "Nutrition"],
  ["OBGY", "Obstetrics and Gynecology"],
  ["OPRE", "Operations"],
  ["OPHT", "Ophthalmology"],
  ["ORBH", "Organizational Behavior"],
  ["OTOL", "Otolaryngology"],
  ["PATH", "Pathology"],
  ["PEDC", "Pediatric Cardiology"],
  ["PEDS", "Pediatrics"],
  ["PHRM", "Pharmacology"],
  ["PHIL", "Philosophy"],
  ["PMRH", "Physical Medicine and Rehabilitation"],
  ["PHYS", "Physics"],
  ["PHOL", "Physiology & Biophysics"],
  ["POSC", "Political Science"],
  ["PQHS", "Population and Quantitative Health Sciences"],
  ["PCHN", "Prevention Center for Healthy Neighborhoods"],
  ["PSCL", "Psychiatry"],
  ["PSCLSCI", "Psychological sciences"],
  ["QHSC", "Quantitative Health Sciences"],
  ["QCMP", "Quantum Computing"],
  ["RAON", "Radiation Oncology"],
  ["RADI", "Radiology"],
  ["RLGN", "Religious Studies"],
  ["RBIO", "Reproductive Biology"],
  ["ROMHMC", "Research Office MHMC"],
  ["DENT", "School of Dental Medicine"],
  ["SCCH", "Schubert Center for Child Studies"],
  ["SLPM", "Sleep Medicine"],
  ["SJI", "Social Justice Institute"],
  ["SWEL", "Social Welfare"],
  ["SOCI", "Sociology"],
  ["SURG", "Surgery"],
  ["SUST", "Sustainability"],
  ["SCEH", "Swetland Center for Environmental Health"],
  ["SYCE", "Systems & Control Engr"],
  ["THTR", "Theater"],
  ["THON", "Translational Hematology and Oncology"],
  ["UROL", "Urology"],
  ["VSRC", "Visual Sciences Research Center"],
  ["WGSS", "Women's, Gender and Sexuality Studies"],
  ["OTHER", "Others"],
];

// Insert schools
const schoolList = [
  ["CAS", "College of Arts & Sciences"],
  ["ENG", "Case School of Engineering"],
  ["NUR", "School of Nursing"],
  ["SAS", "Mandel Schl of Applied Soc Sci"],
  ["CCM", "Cleve Clinic Lerner Coll Med"],
  ["CIA", "Cleveland Institute of Art"],
  ["CIM", "Cleveland Institute of Music"],
  ["DEN", "School of Dental Medicine"],
  ["LAW", "School of Law"],
  ["MED", "School of Medicine"],
  ["MGT", "Weatherhead Schl of Management"],
  ["UH", "University Hospitals"],
  ["VA", "Veteran's Administration"],
  ["CCF", "Cleveland Clinic"],
  ["CMNH", "Cleveland Museum of Natural History"],
  ["GRS", "School of Graduate Studies"],
  ["UGEN", "University General"],
  ["EMG", "Schools of Engineering & Management"],
];

const researchCategoryVsGroup = {
  "Arts & Humanities": ["ARTS"],
  Engineering: ["BIOTECH", "MATERIAL", "MECH", "CIVIL", "ECE"],
  "Computer and Data Sciences / Data Analytics": ["CSDS"],
  "Life Sciences": ["BIOCHEM", "BIOLOGY", "NEURO"],
  "Nursing, Social Sciences, and/or Management": ["SOCIAL", "MGMT", "NURSING"],
  "Physical Sciences and Mathematics": ["PHYSICAL_SCIENCE", "MATHS"],
};

const majorVsDeptMap = {
  BIOTECH: {
    majors: ["BME"],
    departments: ["BMEG", "CBPD", "CIMR", "CRGM", "OTHER"],
  },
  MATERIAL: {
    majors: ["MSE", "CHEN", "PSE"],
    departments: ["EMSE", "EMAC"],
  },
  MECH: {
    majors: ["AERO", "MECH", "EPHY", "GENE"],
    departments: ["EMAE"],
  },
  CIVIL: {
    majors: ["CIV", "PARCH"],
    departments: ["CVEN"],
  },
  ECE: {
    majors: ["EE", "SCE"],
    departments: ["SYCE", "ECSE"],
  },
  BIOCHEM: {
    majors: ["BIOC", "NUTR", "CHEM", "NBM"],
    departments: [
      "BIOC",
      "CHEM",
      "CBEN",
      "MOLM",
      "MVIR",
      "MCN",
      "CSHS",
      "DERM",
      "BCRN",
      "NTRN",
    ],
  },
  BIOLOGY: {
    majors: ["SYSB", "BIOL", "NSCI", "EVOB", "CHBI"],
    departments: [
      "MBIO",
      "BIOLSCI",
      "BIOL",
      "ANAT",
      "BETH",
      "CCCC",
      "RBIO",
      "GENE",
      "CANB",
      "DHRI",
      "EBIO",
      "CTSR",
      "GENM",
      "GMSCCC",
      "GMSCGHD",
      "BHI",
      "CGHD",
      "EPCC",
      "IPIO",
      "INBI",
      "INFD",
      "INFI",
      "ITMM",
      "IBMS",
      "MID",
      "MSTP",
      "MEDI",
      "MEDMHMC",
    ],
  },
  NEURO: {
    majors: ["COGS", "ORIG", "NEUR"],
    departments: [
      "CVMS",
      "CVRI",
      "COGS",
      "MCB",
      "MGI",
      "MHO",
      "NSUH",
      "NEUR",
      "NEUS",
      "OBGY",
      "OPHT",
      "OTOL",
      "PATH",
      "PEDC",
      "PEDS",
      "PHRM",
      "PMRH",
      "PHOL",
      "RAON",
      "RADI",
      "ROMHMC",
      "DENT",
      "SLPM",
      "SURG",
      "THON",
      "UROL",
      "VSRC",
    ],
  },
  NURSING: {
    majors: ["NURS"],
    departments: ["CCHP", "FMCH", "NURS"],
  },
  SOCIAL: {
    majors: [
      "ANES",
      "ANTH",
      "CLAS",
      "COMS",
      "ENGGEO",
      "ENVS",
      "GEOL",
      "GERO",
      "HIST",
      "HPS",
      "PHIL",
      "PSY",
      "RLST",
      "SOC",
      "WGSS",
    ],
    departments: [
      "ANTH",
      "APTC",
      "BCVP",
      "CLSC",
      "COSI",
      "EEPS",
      "GEOL",
      "HSTY",
      "INAM",
      "LAW",
      "LAWCP",
      "LLM",
      "NIMIC",
      "PHIL",
      "PCHN",
      "PSCL",
      "PSCLSCI",
      "RLGN",
      "SJI",
      "SWEL",
      "SOCI",
      "SUST",
      "SCEH",
      "WGSS",
    ],
  },
  MGMT: {
    majors: ["ACC", "BIT", "BMGT", "ECON", "FIN", "INTS", "POSC"],
    departments: [
      "ACCT",
      "BAFI",
      "DGA",
      "DESN",
      "ECON",
      "MGMT",
      "MORE",
      "OPRE",
      "ORBH",
      "POSC",
    ],
  },
  PHYSICAL_SCIENCE: {
    majors: ["ASTR", "PHYS"],
    departments: ["ASTR", "CPBI", "PHYS", "QCMP"],
  },
  MATHS: {
    majors: ["APPM", "MATH", "MATHPHYS", "STAT"],
    departments: ["MATH", "PQHS", "QHSC"],
  },
  ARTS: {
    majors: [
      "ARTED",
      "ARTH",
      "ASST",
      "CHIN",
      "DANC",
      "ENGL",
      "FREN",
      "FFS",
      "GERM",
      "JPN",
      "MKT",
      "MUS",
      "MUSED",
      "SPAN",
      "TEED",
      "THAR",
      "WLIT",
    ],
    departments: [
      "ARTH",
      "BAKN",
      "CMNH",
      "DANC",
      "EDUC",
      "ENGL",
      "MSAS",
      "MLIT",
      "MUSC",
      "SCCH",
      "THTR",
    ],
  },
  CSDS: {
    majors: ["CENG", "CS", "DSA"],
    departments: ["CSDS", "CENG", "CIS"],
  },
};

const studentFields = {
  userId: "User Id",
  networkId: "Net Id",
  memberId: "Member Id",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  gender: "Gender",
  accountType: "Account Type",
  submissionId: "Submission Id",
  startedOn: "Started On",
  submittedOn: "Submitted On",
  lastUpdatedOn: "Last Updated On",
  approvalDate: "Approval Date",
  approvalStatus: "Approval Status",
  approvalMessage: "Approval Message",
  studentTags: "Student Tags",
  memberTags: "Member Tags",
  submissionTags: "Submission Tags",
  invitedTime: "Invited Time",
  notes: "notes",
  participantMajor: "Participant Major",
  participantSchool: "Participant School",
  additionalPresenters: "Are there additional presenters for this project?",
  projectTitle: "Project Title (this should match your abstract)",
  keywords: [1, 2, 3].map((i) => `Key Word or Phrase #${i}`),
  mentor: {
    firstName: " Faculty/Project Mentor First Name",
    lastName: " Faculty/Project Mentor Last Name",
    email: "Faculty/Project Mentor Email",
    department: "Faculty Mentor Department",
    school: "Faculty Mentor's School / Affiliation",
  },
  isMentorPrimaryInvestigator:
    "Is your Faculty/Project Mentor also the Primary Investigator (person overseeing the grant/lab)?",
  isCapstoneProject: "Is this a Capstone Project?",
  readyToSubmitAbstract: "Are you prepared to submit your abstract now?",
  abstractDocumentSubmission: "Abstract Document Submission",
  abstractText: "Abstract or Creative Statement Text (275 words max)",
  abstractReviewers: "Abstract Reviewer(s)",
  principalInvestigator: {
    firstName: "Principal Investigator First Name",
    lastName: "Principal Investigator Last Name",
    email: "Principal Investigator Email",
    department: "Principal Investigator Department",
    school: "Principal Investigator School / Affiliation",
  },
  capstoneInstructor: {
    firstName: "Capstone Instructor First Name",
    lastName: "Capstone Instructor Last Name",
    email: "Capstone Instructor Email",
    department: "Capstone Instructor Department",
    school: "Capstone Instructor School / Affiliation",
  },
  additionalPresentersCount:
    "How many additional individuals will be presenting this research project?",
  presenters: [2, 3, 4, 5, 6, 7, 8].map((i) => ({
    name: `Presenter #${i} Name`,
    major: `Presenter #${i} Major`,
    school: `Presenter #${i} School`,
  })),
  getJudged:
    "Would you like your research poster to be judged by a faculty, staff member, professional, or researcher?",
  researchCategory: "Research Category",
  schubertCenterAward:
    "The Schubert Center for Child Studies provides awards for outstanding projects related to children and/or adolescents. Would you like to be grouped with similar focused projects and considered for an award?",
  session: "When would you prefer to present your research during the event?",
  posterBoardSize: "What size poster board will you need?",
  needTableOrChairs: "Will you need a table or chairs?",
  needElectricity: "Will you need electricity?",
  researchProtocolUnderstanding:
    "Please check that you have read the Research Protocol Understanding.",
  posterNumber: "Poster Number",
};

const positionMapping = {
  "Post Doctoral Scholar/Fellow": "POST_DOC",
  "Master's Student": "MASTERS_STUDENT",
  "Staff/Faculty": "STAFF_FACULTY",
  "Doctoral Student": "DOCTORAL_STUDENT",
  "Medical Students": "MEDICAL_STUDENT",
  Other: "OTHER",
};

const judgeFields = {
  userId: "User Id",
  networkId: "Net Id",
  memberId: "Member Id",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  gender: "Gender",
  accountType: "Account Type",
  submissionId: "Submission Id",
  startedOn: "Started On",
  submittedOn: "Submitted On",
  lastUpdatedOn: "Last Updated On",
  approvalDate: "Approval Date",
  approvalStatus: "Approval Status",
  approvalMessage: "Approval Message",
  studentTags: "Student Tags",
  memberTags: "Member Tags",
  submissionTags: "Submission Tags",
  invitedTime: "Invited Time",
  notes: "notes",
  position: "What is your position?",
  positionComment: "[Comment] What is your position?",
  department: "Please identify your department",
  otherDepartment:
    "If your department is not listed above, please select 'Other' and specify your department here.",
  school: "Please identify your school.",
  judgingCategory: "In which category do you want to judge?",
  discipline:
    "Discipline/Specific area of expertise (please be as broad as possible; it helps in making assignments)",
  keywords: [1, 2, 3].map(
    (i) => `Please provide keywords ${i} that describes your work`
  ),
  judgeOutside: "Are you willing to judge outside your area of expertise?",
  session: "Please inform us of your availability",
  judgeCount: "How many presentations are you willing to judge per session.",
  mentor: {
    firstName: "Principal Investigator First Name, if applicable",
    lastName: "Principal Investigator Last Name, if applicable",
    email: "Principal Investigator Email, if applicable",
    department: "Principal Investigator Department, if applicable",
    school: "Principal Investigator School, if applicable",
  },
  reviewSummerFunding:
    "ONE ADDITIONAL OPPORTUNITY: Are you willing to review applications for URO summer funding? We expect the reviews will take place in late February through Mid-March (2025).",
};

const validSessions = [
  "11:30am - 12:45pm",
  "12:45pm - 2:00pm",
  "The entire event (11:30am - 2pm)",
  "Either",
];
const validBoardSizes = ['32"x40"', '40"x60"'];
const validAwardCategories = [
  "Arts & Humanities",
  "Engineering",
  "Computer and Data Sciences / Data Analytics",
  "Life Sciences",
  "Nursing, Social Sciences, and/or Management",
  "Physical Sciences and Mathematics",
];
const validNeeds = [
  'One 48"x30" table with two chairs',
  "One chair only (no table)",
  "No table or chairs needed",
];

const judgeHeaders = [
  COLUMN.Judges.FirstName,
  COLUMN.Judges.LastName,
  COLUMN.Judges.NetworkId,
  "Assigned Count",
  "Remaining Count",
  COLUMN.JudgeProjectMapping.Session,
  "Other",
  ...[1, 2, 3, 4, 5, 6].flatMap((i) => {
    return [
      COLUMN.Students.FullName + i,
      COLUMN.Students.NetworkId + i,
      COLUMN.Projects.Title + i,
      COLUMN.Projects.ResearchCategory + i,
      COLUMN.Projects.Keyword1 + i,
      COLUMN.Projects.Keyword2 + i,
      COLUMN.Projects.Keyword3 + i,
      COLUMN.Students.MajorCodes + i,
      COLUMN.Students.School + i,
      COLUMN.Projects.PosterNumber + i,
    ];
  }),
];

const studentHeaders = [
  COLUMN.Students.FullName,
  COLUMN.Students.NetworkId,
  COLUMN.Projects.Title,
  COLUMN.Projects.ResearchCategory,
  COLUMN.Students.MajorCodes,
  COLUMN.Students.School,
  ...[1, 2].flatMap((i) => {
    return [
      COLUMN.Judges.FirstName + i,
      COLUMN.Judges.LastName + i,
      COLUMN.Judges.NetworkId + i,
      COLUMN.JudgeProjectMapping.Session + i,
      COLUMN.Judges.Keyword1 + i,
      COLUMN.Judges.Keyword2 + i,
      COLUMN.Judges.Keyword3 + i,
      COLUMN.Judges.Position + i,
      COLUMN.Judges.AssignedCount + i,
      COLUMN.Judges.RemainingCount + i,
      COLUMN.Projects.ResearchCategory + i,
      COLUMN.Judges.DepartmentCode + i,
      COLUMN.Judges.School + i,
      COLUMN.JudgingScenario.JudgeOutside + i,
    ];
  }),
];

const judgeString = "Judge";
const studentString = "Student";
const projectString = "Project";

module.exports = {
  majorList,
  departmentList,
  schoolList,
  studentFields,
  judgeFields,
  validSessions,
  validBoardSizes,
  validAwardCategories,
  validNeeds,
  positionMapping,
  majorVsDeptMap,
  researchCategoryVsGroup,
  judgeHeaders,
  studentHeaders,
  judgeString,
  studentString,
  projectString,
};
